apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-lgtm
  name: otel-lgtm
spec:
  ports:
  - name: grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: otel-lgtm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-lgtm
  labels:
    app: otel-lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-lgtm
  template:
    metadata:
      labels:
        app: otel-lgtm
    spec:
      containers:
        - name: otel-lgtm
          image: grafana/otel-lgtm
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 3000
