apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  labels:
    app: products-service
spec:
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: products-service-image
          ports:
            - containerPort: 3001
          env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: 'http://jaeger-collector.default.svc.cluster.local:4318'
          - name: OTEL_SERVICE_NAME
            value: 'Products Service'
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: 'service.version=4.2.0,service.namespace=default,deployment.environment=dev'
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    app: products-service
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: products-service
