apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: cart-service-image
          ports:
            - containerPort: 8080
          env:
          - name: PRODUCTS_SERVICE_URL
            value: 'http://products-service.default.svc.cluster.local:8081/api/products'
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: 'http://otel-lgtm:4318'
          - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
            value: 'http://otel-lgtm:4317'
          - name: OTEL_EXPORTER_OTLP_LOGS_PROTOCOL
            value: 'grpc'
          - name: OTEL_SERVICE_NAME
            value: 'Cart Service'
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: 'service.version=0.0.6,service.namespace=default,deployment.environment=dev'
